### ISSUE TITLE
Disassembly fails on PE files

### ISSUE THREAD

**Issue by js75** [joelpx/plasma#55]
When trying a random PE file (I'm on Linux) the script fails with the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/plasma", line 9, in <module>
    load_entry_point('plasma==1.0', 'console_scripts', 'plasma')()
  File "/usr/lib/python3.5/site-packages/plasma-1.0-py3.5.egg/plasma/main.py", line 44, in console_entry
    if not gctx.load_file():
  File "/usr/lib/python3.5/site-packages/plasma-1.0-py3.5.egg/plasma/lib/__init__.py", line 195, in load_file
    self.db)
  File "/usr/lib/python3.5/site-packages/plasma-1.0-py3.5.egg/plasma/lib/disassembler.py", line 77, in __init__
    self.binary.load_symbols()
  File "/usr/lib/python3.5/site-packages/plasma-1.0-py3.5.egg/plasma/lib/fileformat/binary.py", line 386, in load_symbols
    self.__demangle_symbols()
  File "/usr/lib/python3.5/site-packages/plasma-1.0-py3.5.egg/plasma/lib/fileformat/binary.py", line 353, in __demangle_symbols
    if n.startswith("_Z") or n.startswith("__Z"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

Installed dependencies:

python 3.5.1
capstone 3.0.4
python-pyelftools 0.23
python-pefile 2016.3.4
python-msgpack 0.4.7
binutils 2.26

I don't think that it matters but I'm using Arch Linux on x86_64.

**Comment by joelpx** [comment]
I'm also on Archlinux x64. Unfortunately, I haven't found a PE written in c++ and I can't compile a test file, so I couldn't reproduce your bug.

Did you try with the repo https://github.com/mlaferrera/python3-pefile instead of the pefile package present in the AUR ?

Thanks.

**Comment by joelpx** [comment]
Can you confirm this is ok for you ? I didn't see that there is now an official port for python3 (the one which is in the AUR package).

**Comment by js75** [comment]
Sorry for the late response. The error message is gone, so I suppose this is fixed.

However, it is now complaining about "symbol main or _main not found", I assume this is because the PE file in question has a WinMain. Any possibility to add support for that?

**Comment by joelpx** [comment]
Generally it prints this because the file was stripped, and the solution is to start at the entry point with the command `v EP`. Then you have to find the main function.
Yes I can add a test for WinMain, can you just verify if the symbol is exactly "WinMain" ?
