### ISSUE TITLE
Curses issue?

### ISSUE THREAD

**Issue by IsaacWoods** [joelpx/plasma#59]
This looks like a really cool project. However, after installing all the dependencies and then Plasma, running and then giving the command `v main` gives this:
```
Traceback (most recent call last):
                                    File "/usr/local/lib/python3.4/dist-packages/plasma-1.0-py3.4-linux-x86_64.egg/plasma/lib/ui/console.py", line 526, in exec_command
                                                                 c.callback_exec(args)
                                                                                        File "/usr/local/lib/python3.4/dist-packages/plasma-1.0-py3.4-linux-x86_64.egg/plasma/lib/ui/console.py", line 655, in __exec_v
       Visual(self.gctx, ctx, self.analyzer, self.api)
                                                        File "/usr/local/lib/python3.4/dist-packages/plasma-1.0-py3.4-linux-x86_64.egg/plasma/lib/ui/visual.py", line 102, in __init__
                                                                                curses.init_pair(1, 253, 66) # for the highlight search
                             _curses.error: init_pair() returned ERR
```

**Comment by joelpx** [comment]
Thank you !
Is your terminal supports 256 colours ? Run `tput colors` to see if it returns 256.
Please check this issue #58, maybe it the same as yours.

**Comment by IsaacWoods** [comment]
Sorry, I completely missed that issue. `tput colors` only returned 8, but adding the correct environment variable to my `.bashrc` seemed to do the trick. Perhaps `requirements.sh` should check for a 256-colour terminal?

**Comment by joelpx** [comment]
I have added an error test for this problem in the commit a0631b8d35f54f2032de77b1744358ab3d8d0c48
